SELECT A.PRODUCT_ID,A.PRODUCT_NAME,A.PRICE * SUM(B.AMOUNT)  AS TOTAL_SALES
FROM FOOD_PRODUCT A JOIN FOOD_ORDER B USING(PRODUCT_ID)
WHERE B.PRODUCE_DATE LIKE '2022-05%'

GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID
