SELECT M.MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d')
    FROM REST_REVIEW A
    JOIN (SELECT MEMBER_ID 
                FROM REST_REVIEW
                GROUP BY MEMBER_ID
                ORDER BY COUNT(*) DESC
                LIMIT 1) B
      ON A.MEMBER_ID = B.MEMBER_ID
    JOIN MEMBER_PROFILE M
      ON M.MEMBER_ID = A.MEMBER_ID
    ORDER BY REVIEW_DATE, REVIEW_TEXT