
WITH sub AS (
    SELECT MEMBER_ID, COUNT(MEMBER_ID)
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) desc
    LIMIT 1
)
SELECT  M.MEMBER_NAME,R.REVIEW_TEXT,DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R USING (MEMBER_ID)
WHERE MEMBER_ID = (SELECT MEMBER_ID
                   FROM sub)
ORDER BY REVIEW_DATE, REVIEW_TEXT


