SELECT ICECREAM_INFO.INGREDIENT_TYPE,sum(FIRST_HALF.TOTAL_ORDER) as TOTAL_ORDER
from FIRST_HALF,ICECREAM_INFO
where  FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
group by ICECREAM_INFO.INGREDIENT_TYPE
order by 2