SELECT CONCAT('/home/grep/src/',b.BOARD_ID,'/', b.file_id, b.file_name, b.file_ext) AS FILE_PATH
FROM USED_GOODS_BOARD a
JOIN USED_GOODS_FILE b USING (BOARD_ID)
WHERE VIEWS = (SELECT MAX(VIEWS) 
             FROM USED_GOODS_BOARD)
ORDER BY b.FILE_ID DESC
